package com.cdxxgc.expressagesearchdemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cdxxgc.expressagesearchdemo.entity.Recorde;
import com.cdxxgc.expressagesearchdemo.entity.User;

import com.cdxxgc.expressagesearchdemo.db.RecordeDao;
import com.cdxxgc.expressagesearchdemo.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordeDaoConfig;
    private final DaoConfig userDaoConfig;

    private final RecordeDao recordeDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordeDaoConfig = daoConfigMap.get(RecordeDao.class).clone();
        recordeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        recordeDao = new RecordeDao(recordeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Recorde.class, recordeDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        recordeDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public RecordeDao getRecordeDao() {
        return recordeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
